language: php
php:
- 7.0
branches:
  only:
    - master

sudo: required

before_script:
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd /home/travis/build
- mkdir artifacts
- cd /home/travis/build/artifacts

script:
- curl -sL https://raw.githubusercontent.com/ImagicalCorp/php-build-scripts/master/plugswork.sh | bash
- cd plugins
- git clone https://github.com/$REPO_OWNER/$REPO_NAME
- cd $REPO_NAME
- rm -rf .git*
- cd ../..

after_script:
- cd /home/travis/build
- git config --global user.email "$PUSH_REPO_ESUER"
- git config --global user.name "$PUSH_REPO_USER"
- git clone --branch=$PUSH_REPO_BRANCH https://github.com/$PUSH_REPO_OWNER/$PUSH_REPO_NAME
# You should copy the artifacts from the build as shown below
- cp /home/travis/build/artifacts/plugins/ImagicalDevTools//$REPO_NAME* /home/travis/build/$PUSH_REPO_NAME/$REPO_NAME-$TRAVIS_JOB_ID.phar
- cp /home/travis/build/artifacts/plugins/ImagicalDevTools//$REPO_NAME* /home/travis/build/$PUSH_REPO_NAME/service-download/$REPO_NAME.phar
- cd /home/travis/build/$PUSH_REPO_NAME
- git add $REPO_NAME-$TRAVIS_JOB_ID.phar
- git add service-download/$REPO_NAME.phar
- ls > list.txt
- echo >> list.txt
- echo "This is a directory listing of the root directory of the $REPO_NAME release download website. Copy the file name and paste it in the URL bar after deleting \"list.txt\". You can also alternatively download files using a shell script by downloading the file from $DIRECT_DL_URI. The download link for the latest plugin build is $DOWNLOAD_URI" >> list.txt
- git add list.txt
- git commit -am "$COMMIT_MESSAGE"
- git push https://$PUSH_REPO_USER:$GITHUB_API_KEY@github.com/$PUSH_REPO_OWNER/$PUSH_REPO_NAME $PUSH_REPO_BRANCH &>secret

# VARIABLES NEED TO BE SET BELOW
env:
 global:
  - REPO_OWNER="ImagicalGamer"
  - REPO_NAME="SurvivalGames"
  - PUSH_REPO_OWNER="ImagicalGamer"
  - PUSH_REPO_NAME="SurvivalGames"
  - PUSH_REPO_USER="ImagicalGamer"
  - PUSH_REPO_EUSER="imagicalgamer@outlook.com"
  - PUSH_REPO_BRANCH="master"
  - COMMIT_MESSAGE="Add latest commits!"
  - DATATP="phar"
  - DOWNLOAD_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/$REPO_NAME-$TRAVIS_JOB_ID.$DATATP" 
  - DIRECT_DL_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/service-download/$REPO_NAME.$DATATP"
